# Generated by Django 4.2.1 on 2023-05-19 03:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oai',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
