# Generated by Django 4.2.1 on 2023-05-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0002_alter_oai_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oai',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
