# Generated by Django 4.2.1 on 2023-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
