# Generated by Django 4.2.1 on 2023-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0006_document_doc_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(blank=True, max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_path',
        ),
    ]
