# Generated by Django 4.2.1 on 2023-05-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0007_documentpath_remove_document_doc_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='document_path',
        ),
    ]
