# Generated by Django 4.2.1 on 2023-05-22 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0009_documentquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
