# Generated by Django 4.2.1 on 2023-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai', '0010_document_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
